### ISSUE TITLE
Design Template

### ISSUE THREAD

**Issue by Braggedtooth** [chas-academy/u05-imdb-clone-team4#10]
### The design of the website should communicate at first glance  
1. what sort of website it is 
2.  what functionality are available to the user 
3.  a visual feedback to the user ex . green is success
4.  a concise and consistent layout that displays relevant information relative to user actions or query. 

### To achieve this we need to think about the following 
- color 
- typography
- acessiblity
- structure
- user stories

**Comment by stenwall** [comment]
Things we talked about on the meeting Friday 19/2:
- About the card grid layout:
    - It's nice with simple cards with sharp edges
    - You should be able to do one or two actions with the cards, not more (e.g. click on a flag/banner/star on the card to get a pop-up preview where you can add the film to your list, and click anywhere else on the card to get to the movie page)
    - The cards should contain short, concise and relevant information
    - The text/info under the card should be connected to the picture (not like on youtube)
- It's nice to have the page we as wide as the browser, if we are using the card grid layout
- The page should be dark but not black, and have a color theme in buttons, logo, headlines etc (like the yellow color on [IMDb](https://www.schemecolor.com/imdb.php) or the pink on [Svensk Filmdatabas](http://www.svenskfilmdatabas.se/sv/)), so that the images from the movies pop out, but it's still important that the page it self has an identity

Questions to answer:
- How should the search-function work? Do we want to choose search category before we search, or filter the results?
- What should we have on the home page (lists? news? suggestions?), and in which order?

Some links:
[Nice card design](https://dribbble.com/shots/1611422-Traveler-Responsive-Blog-Theme/attachments/250092)
[Like the design if we switch placement of buttons, menu and colors](https://www.awwwards.com/websites/)
[The sketch in Figma](https://www.figma.com/files/team/944164298822718087/IMDB-CLONE-U05)

**Comment by stenwall** [comment]
Suggestion for [color theme](https://color.adobe.com/sv/Movie-color-theme-17066749):


![](https://i.imgur.com/v7m2VWm.jpeg)

**Comment by johannasjo** [comment]
Design repo here: https://github.com/johannasjo/basic-design-u05
To have look go here: https://johannasjo.github.io/basic-design-u05/
